
- defaults:
    name: global


- project:
    name: script.mpe

    branch: test
    vendor-path: dotmpe/script.mpe

    jobs:
    - '{name}-gh-travis':
        disabled: false
        title: 'script.mpe [gh,public,travis] ({branch})'
        htmlDescription: ''
        project-src: '*.sh,*.py'
        email-to: ''
        build-summary-image:
        email-individuals: false

    - '{name}-local-gh-travis':
        disabled: false
        title: 'script.mpe [gh,travis] ({branch})'
        htmlDescription: ''
        project-src: '*.sh,*.py'
        email-to: ''
        build-summary-image:
        email-individuals: false
        credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'


    - '{name}-local-gh':
        disabled: false
        title: 'script.mpe [gh,local] ({branch})'
        htmlDescription: ''
        project-src: '*.sh,*.py'
        email-to: ''
        build-summary-image:
        email-individuals: false
        credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'
        builders:
        - shell: echo OK

