
- project:
    name: script.mpe

    branch: test
    vendor-path: dotmpe/script.mpe
    htmlDescription: ''
    project-src: '*.sh,*.py'
    email-to: ''
    build-summary-image:
    email-individuals: false
    credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'

    # XXX hacky hack hack
    box,str: '{box,str}'
    bats-tests: '{box,str}'
    #bats-tests: '\{box,str\}'

    # FIXME: travis build fails on TB config parts
    # XXX: want to use branch checkout? but not working
    jobs:
    - '{name}-gh-travis':
        disabled: true
        title: 'script.mpe [gh,public,travis] ({branch})'

    - '{name}-local-gh-travis':
        disabled: true
        title: 'script.mpe [gh,travis] ({branch})'

    - '{name}-local-gh':
        disabled: false
        title: 'script.mpe [gh,local,no-test] ({branch})'
        htmlDescription: 'Running some bats test to see if they go, without parsing results'
        builders:
        - shell: |
            mkdir -vp ./build
            echo pwd=$pwd
            cd && ln -s /home/travis/build/dotmpe/script.mpe bin
            echo pwd=$pwd
            export PATH=$PATH:$HOME/usr/bin/
            bats --version
            export PYTHON_PATH=$PYTHON_PATH:$HOME/lib/py
            export JTB_HOME=$HOME/build/jtb
            export PATH=$PATH:$HOME/bin/
            export PREFIX=~/
        - shell: |
            cd
            echo pwd=$pwd
            box -v
            htd -v
            match.sh -v
            cd $WORKSPACE
            bash -c './test/{bats-tests}-spec.bats'

    - '{name}-local-gh-bats':
        disabled: false
        title: 'script.mpe [gh,local,bats] ({branch})'
        builders:
#        - shell: |
#            . ./install-dependencies.sh && install_bats
        - shell: |
            mkdir -vp ./build
            export PATH=$PATH:$HOME/usr/bin/
            bats --version
            export PYTHON_PATH=$PYTHON_PATH:$HOME/lib/py
            export JTB_HOME=$HOME/build/jtb
            export PATH=$PATH:$HOME/bin/
            export PREFIX=~/
            ./box -v
            ./htd -v
            ./match.sh -v
            bash -c './test/{bats-tests}-spec.bats > ./build/test-results.tap'


