
- project:
    name: script.mpe

    branch: dev
    vendor-path: dotmpe/script.mpe
    htmlDescription: ''
    project-src: '*.sh,*.py'
    email-to: ''
    build-summary-image:
    email-individuals: false
    credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'

    # XXX hacky hack hack
    box,str: '{box,str}'
    bats-tests: '{box,str}'
    # XXX bats-tests: '{{box,str}}'
    # XXX bats-tests: '\{box,str\}'


    jobs:

    #
    # Two partially pre-scripted jobs Using the .travis.yml 
    # build config.
    #
    # FIXME: travis build fails on TB config parts
    # XXX: want to use branch checkout? but not working
    - '{name}-gh-travis':
        disabled: true
        title: 'script.mpe [gh,public,travis] ({branch})'

    - '{name}-local-gh-travis':
        disabled: true
        title: 'script.mpe [gh,travis] ({branch})'

    #
    # Two custom script Github checkouts for testing.
    # One without and one with TAP test result publishing.
    #

    - '{name}-local-gh':
        disabled: false
        title: 'script.mpe [gh,local,no-test] ({branch})'
        htmlDescription: 'Running some bats test to see if they go, without parsing results'
        builders:
        - shell: |

            export PATH=$PATH:$HOME/usr/bin/
            bats --version

            rm -rf $HOME/bin
            ln -s $WORKSPACE $HOME/bin
            export PATH=$PATH:$HOME/bin/
            export PYTHON_PATH=$PYTHON_PATH:$HOME/lib/py
            export JTB_HOME=$HOME/build/jtb

            export PREFIX=$WORKSPACE
            export TRAVIS_SKIP=1
            export JENKINS_SKIP=1
            ./box help
            bash -c './test/{bats-tests}-spec.bats'


    - '{name}-local-gh-bats':
        disabled: false
        title: 'script.mpe [gh,local,bats] ({branch})'
        builders:
        - shell: |

            export PATH=$PATH:$HOME/usr/bin/
            bats --version

            rm -rf $HOME/bin
            ln -s $WORKSPACE $HOME/bin
            export PATH=$PATH:$HOME/bin/
            export JTB_HOME=$HOME/build/jtb
            export PYTHON_PATH=$PYTHON_PATH:$HOME/lib/py

            box -v
            htd -v
            match.sh -v

            export PREFIX=$WORKSPACE
            export TRAVIS_SKIP=1
            export JENKINS_SKIP=1
            mkdir -vp ./build

            test -n "$SUITE" && {{
              SPECS=
              for SPEC in $SUITE
              do
                SPECS="$SPECS ./test/$SPEC-spec.bats"
              done
            }} || test -n "$SPEC" && {{
              SPECS="./test/$SPEC-spec.bats"
            }} || {{
              SPECS=./test/*-spec.bats
            }}

            bats $SPECS > ./build/test-results.tap

    #
    # A job to test/update this build config file, if either JJB, JTB or
    # this repo changes.
    #


