
- project:
    name: script.mpe

    branch: test
    vendor-path: dotmpe/script.mpe

    # FIXME: travis build fails on TB config parts
    # XXX: want to use branch checkout? but not working
    jobs:
    - '{name}-gh-travis':
        disabled: false
        title: 'script.mpe [gh,public,travis] ({branch})'
        htmlDescription: ''
        project-src: '*.sh,*.py'
        email-to: ''
        build-summary-image:
        email-individuals: false

    - '{name}-local-gh-travis':
        disabled: true
        title: 'script.mpe [gh,travis] ({branch})'
        htmlDescription: ''
        project-src: '*.sh,*.py'
        email-to: ''
        build-summary-image:
        email-individuals: false
        credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'

    - '{name}-local-gh':
        disabled: false
        title: 'script.mpe [gh,local,no-test] ({branch})'
        htmlDescription: ''
        project-src: '*.sh,*.py'
        email-to: ''
        build-summary-image:
        email-individuals: false
        credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'
        builders:
        - shell: echo No-op

    - '{name}-local-gh-bats':
        disabled: false
        title: 'script.mpe [gh,local,bats] ({branch})'
        htmlDescription: ''
        project-src: '*.sh,*.py'
        email-to: ''
        build-summary-image:
        email-individuals: false
        credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'
        builders:
        - shell: |
            export PATH=$PATH:$HOME/bin/
            export PATH=$PATH:$HOME/usr/bin
            export PYTHON_PATH=$PYTHON_PATH:$HOME/lib/py
            mkdir -vp build
            ./test/*-spec.bats > build/tests-results.tap


