
# Define jobs using JTB templates

- project:
    name: script.mpe

    branch: dev
    version: 0.0.2 # script-mpe
    jtb-file: .jtb.yml

    vendor-path: dotmpe/script.mpe
    htmlDescription: ''
    project-src: '*.sh,*.py'
    email-to: ''
    build-summary-image:
    email-individuals: false
    credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'

    # XXX hacky hack hack
    box,str: '{box,str}'
    bats-tests: '{box,str}'
    # XXX bats-tests: '{{box,str}}'
    # XXX bats-tests: '\{box,str\}'

    properties: {}
    parameters:
    - hidden:
        name: SCRIPT_MPE_VERSION
        default: '{version}'
    - hidden:
        name: SCRIPT_MPE_JTB_FILE
        default: '{jtb-file}'
    metadata: {}
    publishers: {}

    jobs:

    #
    # Two partially pre-scripted jobs Using the .travis.yml 
    # build config.
    #
    # FIXME: jjb/jnk currently not working with travis build anymore
    # FIXME: travis build fails on TB config parts
    # XXX: want to use branch checkout? but not working
    #
    #- '{name}-gh-travis':
    #    disabled: true
    #    title: 'script.mpe [gh,public,travis] ({branch})'

    #- '{name}-local-gh-travis':
    #    disabled: true
    #    title: 'script.mpe [gh,travis] ({branch})'


    #
    # Two custom script Github checkouts for testing.
    # One without and one with TAP test result publishing.
    #

    - '{name}-gh':
        disabled: true
        title: 'script.mpe [gh,local,no-test] ({branch})'
        htmlDescription: |
          <p>Running some bats test to see if they go, without parsing results.</p>
          <p>Part of <code class="muted">{name}/{version}</code> <code>{file}</code></p>
        restrict-node: ubuntu || treebox
        builders:
        - shell: |
            export PATH=$HOME/.local/bin:$HOME/.basher/bin:$PATH
            Build_Deps_Default_Paths=1 \
            ./install-dependencies.sh -
        - shell: |
            export PATH=$HOME/.local/bin:$HOME/.basher/bin:$PATH
            . ./tools/sh/env.sh
            export TEST_ENV=jenkins
            . ./tools/ci/test.sh
        publishers:
        - tap:
            results: build/test-results.tap
    
    
    #    - '{name}-gh-travis':
    #        disabled: false
    #        title: 'script.mpe [gh,travis] ({branch})'
    #        restrict-node: ubuntu || treebox
    #        properties: []
    #        parameters: []
    #        metadata: []


    - '{name}-gh-bats':
        disabled: false
        title: 'script.mpe [gh,bats] ({branch})'
        htmlDescription: |
          <p>Run some bats tests and publish results</p>
          <p>Part of <code class="muted">{name}/{version}</code> <code>{file}</code></p>
        restrict-node: ubuntu || treebox
        bats-tap-results: build/test-results.tap
        parameters:
        - hidden:
            name: SCRIPT_MPE_VERSION
            default: '{version}'
        - hidden:
            name: SCRIPT_MPE_JTB_FILE
            default: '{jtb-file}'
        - string:
            name: SUITE
            value: main
            default: 
            description: |
              Values: helper util-lib str std os match vc main box-lib box-cmd box
              statusdir htd basename-reg dckr diskdoc esop jsotk-py libcmd_stacked 
              matchbox meta mimereg pd radical
        - bool:
            name: DEBUG
            value: false
        properties: []
        metadata: []
        # TODO: fix JJB serialize choking on non-str: int, float, bool
        #- string:
        #    name: Build_Deps_Default_Paths
        #    value: on
        #    expose-to-env: false
        builders:
        - shell: |
            export PATH=$HOME/.local/bin:$HOME/.basher/bin:$PATH
            Build_Deps_Default_Paths=1 \
            ./install-dependencies.sh -
        - shell: |
            export PATH=$HOME/.local/bin:$HOME/.basher/bin:$PATH
            . ./tools/sh/env.sh
            export TEST_ENV=jenkins
            . ./tools/ci/test.sh



