
# Define jobs using JTB templates

- project:
    name: script.mpe

    branch: dev
    vendor-path: dotmpe/script.mpe
    htmlDescription: ''
    project-src: '*.sh,*.py'
    email-to: ''
    build-summary-image:
    email-individuals: false
    credentials-id: 'f3711d97-0c02-4099-b16f-d6d7fe13d168'

    # XXX hacky hack hack
    box,str: '{box,str}'
    bats-tests: '{box,str}'
    # XXX bats-tests: '{{box,str}}'
    # XXX bats-tests: '\{box,str\}'


    jobs:

    #
    # Two partially pre-scripted jobs Using the .travis.yml 
    # build config.
    #
    # FIXME: travis build fails on TB config parts
    # XXX: want to use branch checkout? but not working
    #- '{name}-gh-travis':
    #    disabled: true
    #    title: 'script.mpe [gh,public,travis] ({branch})'

    #- '{name}-local-gh-travis':
    #    disabled: true
    #    title: 'script.mpe [gh,travis] ({branch})'

    #
    # Two custom script Github checkouts for testing.
    # One without and one with TAP test result publishing.
    #

    - '{name}-local-gh':
        disabled: true
        title: 'script.mpe [gh,local,no-test] ({branch})'
        htmlDescription: 'Running some bats test to see if they go, without parsing results'
        credentials-id: 'f1899d66-848f-43e9-83cf-f26f171a1e27'
        restrict-node: ubuntu || treebox
        parameters: []
        properties: []
        metadata: []
        builders:
        - shell: |
            . ./tools/sh/env.sh
            export TEST_ENV=jenkins
            . ./tools/ci/test.sh

        publishers:
        - tap:
            results: build/test-results.tap


    - '{name}-local-gh-bats':
        disabled: false
        title: 'script.mpe [gh,local,bats] ({branch})'
        credentials-id: 'f1899d66-848f-43e9-83cf-f26f171a1e27'
        restrict-node: ubuntu || treebox
        bats-tap-results: build/test-results.tap
        parameters:
        - string:
            name: SUITE
            value: main
            default: 
            description: |
              Values: helper util-lib str std os match vc main box-lib box-cmd box
              statusdir htd basename-reg dckr diskdoc esop jsotk-py libcmd_stacked 
              matchbox meta mimereg pd radical
        - bool:
            name: DEBUG
            value: false
        properties: []
        metadata: []
        # TODO: fix JJB serialize choking on non-str: int, float, bool
        #- string:
        #    name: Build_Deps_Default_Paths
        #    value: on
        #    expose-to-env: false
        builders:
        - shell: |
            . ./tools/sh/env.sh
            export TEST_ENV=jenkins
            . ./tools/ci/test.sh


