
install: ./install-dependencies.sh

sudo: false
script: make test

branches:
  only:
  - master
#  - dev_taxus
#  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV= CS=dark
#- ENV=testing
#- ENV=production

