sudo: false

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - curl
      - php5-cli
# not allowed:
# - rhash
# - pytz

install:
  - echo "phase Travis install"
  - . ./tools/ci/install.sh

before_script:
  - echo "phase Travis before-script"
  - . ./tools/ci/pre-run.sh

script:
  - echo "phase Travis (test) script"
  - . ./tools/ci/build.sh

env:
  global:
    - CS=dark
    - TRAVIS_SKIP=1
    - TEST_ENV=travis
    - UCONFDIR=$HOME/etc
    - PATH=$PATH:$HOME/bin:$HOME/bin/vendor/.bin:$HOME/usr/bin:$HOME/.local/bin/:/usr/local/bin
    - PYTHONPATH=$PYTHONPATH:$HOME/bin:$HOME/lib/py
      #export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/site-packages
      #export PYTHONPATH=$HOME/.local/lib/python2.7/site-packages:$PYTHONPATH
    - Build_Deps_Default_Paths=1
  matrix:
    #- ENV=dev
    - ENV=jekyll
    - ENV=testing
    #- ENV=production

branches:
  not: []
  #only:
    #  - master
    #  - '/^test.*$/'
    #  - '/^dev.*$/'
    #  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

#deploy:
#  provider: releases
#  api_key: $GH_ACCESS_TOKEN
#  file: script-mpe-$TRAVIS_TAG.tar
#  on:
#    repo: dotmpe/script.mpe
#    tags: true
#    condition: $ENV = production
#
#


