sudo: false

install: ./install-dependencies.sh

before_script:
- 'pip install --user PyYAML'
- 'pip install --user zope.interface'
- 'pip install --user zope.component'
- 'pip install --user jsonschema'
- 'pip install --user sqlalchemy'
- 'export PATH=$PATH:./'
- 'export PATH=$PATH:~/usr/bin'
- 'export PYTHON_PATH=$PYTHON_PATH:~/lib/py'
- 'pwd'

script: make -k test

branches:
  only:
  - master
#  - dev_taxus
#  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV= CS=dark
#- ENV=testing
#- ENV=production

