sudo: false

install:
- "source ./install-dependencies.sh && install_bats"
- "source ./install-dependencies.sh && install_mkdoc"
- "source ./install-dependencies.sh && install_pylib"
- "source ./install-dependencies.sh && install_script"
- "source ./install-dependencies.sh && install_docopt"

addons:
  apt:
    packages:
      - tree
      - realpath
# not allowed    - rhash

before_script:
- 'echo HOME=$HOME PREFIX=$PREFIX pwd=$(pwd)'
- 'mkdir ~/public_html'

# XXX: run these to notice generic problems early. Or maybe should deconstruct
# parts into matrix build
- 'projectdir.sh help'
- 'vc.sh help'
- htd help
- 'pip install --user PyYAML'
- 'pip install --user zope.interface'
- 'pip install --user zope.component'
- jsotk.py -h
- 'npm install parse-torrent lodash'
- 'pip install --user docutils'
- 'pip install --user jsonschema'
- 'pip install --user sqlalchemy'
- 'pip install --user sqlalchemy-migrate'
- 'rm $HOME/bin && ln -s /home/travis/build/dotmpe/script.mpe $HOME/bin'
- 'box version && box -V'
- 'touch /home/travis/.basename-reg.yaml'
- whoami
- hostname


script:
- ./tools/ci/build.sh

env:
  global:
    - CS=dark
    - TRAVIS_SKIP=1
    - UCONFDIR=$HOME/etc
    - PATH=$PATH:$HOME/bin:$HOME/usr/bin:$HOME/.local/bin/
    - PYTHONPATH=$PYTHONPATH:$HOME/bin:$HOME/lib/py
    - Build_Deps_Default_Paths=1
  matrix:
  - ENV= 
#- ENV=testing
#- ENV=production

branches:
  only:
  - master
  - '/^test.*$/'
  - '/^dev.*$/'
  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

#deploy:
#  provider: releases
#  api_key: $GH_ACCESS_TOKEN
#  file: script-mpe-$TRAVIS_TAG.tar
#  on:
#    repo: dotmpe/script.mpe
#    tags: true
#    condition: $ENV = production
#
