sudo: false

install:
- "source ./install-dependencies.sh && install_bats"
- "source ./install-dependencies.sh && install_mkdoc"
- "source ./install-dependencies.sh && install_pylib"
- "source ./install-dependencies.sh && install_script"
- "source ./install-dependencies.sh && install_docopt"

addons:
  apt:
    packages:
      - tree
      - realpath
# not allowed:
# - rhash
# - pytz

before_script:
- 'echo HOME=$HOME PREFIX=$PREFIX pwd=$(pwd)'
- whoami
- hostname

- 'mkdir ~/public_html'
- 'rm $HOME/bin && ln -s /home/travis/build/dotmpe/script.mpe $HOME/bin'
- 'touch /home/travis/.basename-reg.yaml'

- htd help
- 'box version && box -V'
- 'vc.sh help'
- 'projectdir.sh help'

- 'pip install --user pytz'
- 'pip install --user PyYAML'
- 'pip install --user zope.interface'
- 'pip install --user zope.component'
- 'pip install --user objectpath'
- 'pip install --user docutils'
- 'pip install --user jsonschema'
- 'pip install --user sqlalchemy'
- 'pip install --user sqlalchemy-migrate'
- 'npm install parse-torrent lodash'

- radical.py --help
- jsotk.py -h
- jsotk.py from-args foo=bar
- jsotk.py objectpath
      $HOME/bin/test/var/jsotk/2.yaml
      '$.*[@.main is not None]'


script:
- ./tools/ci/build.sh

env:
  global:
    - CS=dark
    - TRAVIS_SKIP=1
    - UCONFDIR=$HOME/etc
    - PATH=$PATH:$HOME/bin:$HOME/usr/bin:$HOME/.local/bin/
    - PYTHONPATH=$PYTHONPATH:$HOME/bin:$HOME/lib/py
    - Build_Deps_Default_Paths=1
  matrix:
  - ENV= 
#- ENV=testing
#- ENV=production

branches:
  only:
    #  - master
    #  - '/^test.*$/'
    #  - '/^dev.*$/'
    #  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

#deploy:
#  provider: releases
#  api_key: $GH_ACCESS_TOKEN
#  file: script-mpe-$TRAVIS_TAG.tar
#  on:
#    repo: dotmpe/script.mpe
#    tags: true
#    condition: $ENV = production
#
