sudo: false

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - curl
      - php5-cli
# not allowed:
# - rhash
# - pytz

install:
  - echo "phase Travis install"
  - 'curl -sS https://getcomposer.org/installer | php -- --install-dir=$HOME/.local/bin --filename=composer'
  - . ./tools/ci/install.sh
  - ~/.local/bin/composer --version
  - composer install
  - touch $HOME/.basename-reg.yaml

before_script:
  - echo "phase Travis before-script"
  - . ./tools/ci/pre-run.sh
  - ~/.local/bin/composer --version
  - ./bin/behat --version

script:
  - echo "phase Travis (test) script"
  - . ./tools/ci/build.sh

env:
  global:
    - CS=dark
    - TRAVIS_SKIP=1
    - TEST_ENV=travis
    - UCONFDIR=$HOME/etc
    - PATH=$PATH:$HOME/bin:$HOME/usr/bin:$HOME/.local/bin/
    - PYTHONPATH=$PYTHONPATH:$HOME/bin:$HOME/lib/py
    - Build_Deps_Default_Paths=1
  matrix:
  - ENV= 
#- ENV=testing
#- ENV=production

branches:
  not: []
  #only:
    #  - master
    #  - '/^test.*$/'
    #  - '/^dev.*$/'
    #  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

#deploy:
#  provider: releases
#  api_key: $GH_ACCESS_TOKEN
#  file: script-mpe-$TRAVIS_TAG.tar
#  on:
#    repo: dotmpe/script.mpe
#    tags: true
#    condition: $ENV = production
#
#


