#os: linux
#dist: precise
#dist: trusty
#dist: xenial

language: python

python: # TODO: keep all builds singular except at dedicated test matrix branch
  - "2.7" # 2.7.14 [2018-12-07] 
  # FIXME: python3 fix (jsotk at least) on other branch
  #- "3" 'Forbidden'
  #- "3.6"
  #- "nightly" # 3.7.0a4+ [2018-12-07] 

addons:
  apt:
    packages:
      - realpath
      - tree
      - uuid-runtime
      - moreutils
      - curl
      - php5-cli
      - posh
      - dash
      - ruby-bundler
#- php5-dom
# not allowed:
# - rhash
# - pytz

services:
- redis-server
- memcached
- couchdb
- docker

# 'sponge' some scripts' output to try to prevent Travis from cutting of build;
# slow buffer?
# but sponged scripts cannot import local env or functions into build context.
#
# Would test sync as alternative but need more syntax either way..
before_install:
  - export scriptname="before-install" before_install_ts="$(date +%s.%N)"
  - . ./tools/ci/env.sh
  - . ./tools/ci/parts/init.sh
  - . ./tools/ci/parts/announce.sh

install:
  - export scriptname=install install_ts="$(date +%s)"
  - note "Starting $scriptname..."
  - . ./tools/ci/parts/install.sh

before_script:
  - export scriptname="before-script" before_script_ts="$(date +"%s.%N")"
  - note "Starting $scriptname..."
  - . ./tools/ci/parts/check.sh

script:
  - export scriptname=script script_ts="$($gdate +"%s.%N")"
  - note "Starting $scriptname..."
  - failed=/tmp/htd-build-test-$(get_uuid).failed
  - . ./tools/ci/parts/build.sh
  - export script_end_ts="$($gdate +"%s.%N")"
  - test "$SHIPPABLE" = true || test ! -e "$failed"
  - note "End of $scriptname"

before_cache:
  - export scriptname=before-cache before_cache_ts="$(date +"%s.%N")"
  - . ./tools/ci/parts/before-cache.sh

cache:
  directories:
     - .htd
     - .redo
     - ./node_modules
     - ./vendor
     - $HOME/.local
     - $HOME/.basher
     - $HOME/.cache/pip
     - $HOME/virtualenv
     - $HOME/.npm
     - $HOME/.composer
     - $HOME/.rvm/
     - $HOME/.statusdir/
     - $HOME/lib
     - $HOME/build/apenwarr
     - $HOME/build/ztombol
     - $HOME/build/bvberkum/user-scripts
     - $HOME/build/bvberkum/user-conf
     - $HOME/build/bvberkum/docopt-mpe
     - $HOME/build/bvberkum/git-versioning
     - $HOME/build/bvberkum/bats-core

after_success:
  - export scriptname=after-success after_success_ts="$(date +"%s.%N")"
  - std_note "End of $scriptname"

after_failure:
  - export scriptname=after-failure after_failure_ts="$(date +"%s.%N")"
  - std_note "End of $scriptname"

after_script:
  - export scriptname=after-script after_script_ts="$(date +"%s.%N")"
  - . ./tools/ci/parts/after.sh
  - . ./tools/ci/parts/publish.sh
  - std_note "End of $scriptname"
  - echo done

#matrix:
#  include: []

env:
  matrix:
    - TEST_ENV=testing TEST_SHELL=sh
  global:
    - ENV_NAME=testing
    - TEST_ENV=travis
    - ENV_D=test:travis
    - CS=dark
    - sudo=
    - UCONFDIR=$HOME/etc
    - PATH=$PATH:$PWD:$PWD/vendor/bin:$HOME/.basher/bin:$HOME/.basher/cellar/bin:$HOME/usr/bin:$HOME/.local/bin/:/usr/local/bin
    - TEST_RESULTS=shippable/testresults/test
    - Build_Deps_Default_Paths=1
    - BATS_REPO=https://github.com/bvberkum/bats-core.git
    - PYTHONPATH=$PYTHONPATH:/home/travis/.local/lib/python2.7/site-packages:$HOME/bin:$HOME/lib/py
    - COUCH_DB=test
    - TMPDIR=/tmp
    # GITHUB_TOKEN
    - secure: "KcpgIZINqays/BZkCYcQTiI3/ACWhRJbLWYD2tHE7GLSTyyBc1nQQWFx3oEZMJcfwUWtHioLx7c7gzO7+UYoOtc3+XfnuTt1g7Fid3xnXE9F5qCTVrIYSuFFT50iDYj2Gp12mRoMwauhvFFRDS3bM/KT/6GOYq9dPdoviDgPtzg="

branches:
  only:
    - master
    # Because shippable does not handle the patterns correctly
    - test
    - dev
    - '/^features\/.*$/'
    - '/^test.*$/'
    - '/^dev.*$/'
    - '/^[0-9]*\.[0-9]*\.[0-9]*/'

#deploy:
#  provider: releases
#  api_key: $GH_ACCESS_TOKEN
#  file: script-mpe-$TRAVIS_TAG.tar
#  on:
#    repo: dotmpe/script.mpe
#    tags: true
#    condition: $ENV = production
#
# Id: script-mpe/0.0.4-dev .travis.yml
