language: python

python:
  - "2.7"
  #- "3.2"
  #- "3.6"
  #- "3.6-dev"
  #- "3.7"
  #- "3.7-dev"
  #- "nightly"

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - curl
      - php5-cli
      - posh
      - dash
      - ruby-bundler
#- php5-dom
# not allowed:
# - rhash
# - pytz

before_install:
  - export scriptname="before-install" before_install_ts="$(date +%s)"
  - . ./tools/ci/env.sh
  - . ./tools/ci/parts/init.sh

install:
  - export scriptname=install install_ts="$(date +%s)"
  - . ./tools/ci/parts/install.sh

before_script:
  - export scriptname="before-script" before_script_ts="$(date +%s)"
  - . ./tools/ci/parts/check.sh

script:
  - export scriptname=script script_ts="$(date +%s)"
  - . ./tools/ci/parts/build.sh

after_script:
  - export scriptname=after_script after_script_ts="$(date +%s)"
  - . ./tools/ci/parts/publish.sh

#after_success:

before_cache:
  - export scriptname=before-cache before_cache_ts="$(date +%s)"
  - rm -f $HOME/.cache/pip/log/debug.log

#cache:
#  directories:
#     - ./node_modules
#     - ./vendor
#     - $HOME/.local
#     - $HOME/.basher
#     - $HOME/.cache/pip
#     - $HOME/virtualenv
#     - $HOME/.npm

#matrix:
#  include: []
#
env:
  matrix:
    - TEST_ENV=testing TEST_SHELL=sh
  global:
    - ENV=
    - CS=dark
    - sudo=
    - TRAVIS_SKIP=1
    - TEST_ENV=travis
    - UCONFDIR=$HOME/etc
    - PATH=$PATH:$PWD:$PWD/vendor/.bin:$HOME/.basher/bin:$HOME/.basher/cellar/bin:$HOME/usr/bin:$HOME/.local/bin/:/usr/local/bin
    - TEST_RESULTS=shippable/testresults/test.tap
    - Build_Deps_Default_Paths=1
    - LOG=$PWD/log.sh
    - BATS_REPO=https://github.com/bvberkum/bats.git
    - PYTHONPATH=$PYTHONPATH:/home/travis/.local/lib/python2.7/site-packages:$HOME/bin:$HOME/lib/py

branches:
  only:
    - master
    - '/^test.*$/'
    - '/^dev.*$/'
    - '/^[0-9]*\.[0-9]*\.[0-9]*/'

#deploy:
#  provider: releases
#  api_key: $GH_ACCESS_TOKEN
#  file: script-mpe-$TRAVIS_TAG.tar
#  on:
#    repo: dotmpe/script.mpe
#    tags: true
#    condition: $ENV = production
#
# Id: script-mpe/0.0.4-dev .travis.yml
