sudo: false

install:
- "source ./install-dependencies.sh && install_bats"
- "source ./install-dependencies.sh && install_mkdoc"
- "source ./install-dependencies.sh && install_pylib"
- "source ./install-dependencies.sh && install_script"

addons:
  apt:
    packages:
# not needed    - tree
# not allowed    - rhash

before_script:
- 'npm install parse-torrent lodash'
- 'pip install --user PyYAML'
- 'pip install --user zope.interface'
- 'pip install --user zope.component'
- 'pip install --user jsonschema'
- 'pip install --user sqlalchemy'
- 'export PATH=$PATH:$HOME/bin/'
- 'export PATH=$PATH:$HOME/usr/bin'
- 'export PYTHON_PATH=$PYTHON_PATH:$HOME/lib/py'
- 'touch /home/travis/.basename-reg.yaml'

script:
- ./test/*-spec.bats
- ./basename-reg ffnnec.py
- ./mimereg ffnenc.py
# FIXME make -k test

branches:
  only:
  - test
#  - dev_taxus
#  - '/^[0-9]*\.[0-9]*\.[0-9]*/'

env:
- ENV= CS=dark TRAVIS_SKIP=1
#- ENV=testing
#- ENV=production

