#language: python
#
#python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  #- "3.3"
#  #- "3.4"
#  #- "3.7"
#  #- "nightly"

addons:
  apt:
    packages:
      - tree
      - realpath
      - uuid-runtime
      - moreutils
      - curl
      - php5-cli
# not allowed:
# - rhash
# - pytz

before_install:
  - . ./tools/ci/init.sh

install:
  - apt-get install python-dev
  - . ./tools/ci/install.sh

before_script:
  - . ./tools/ci/check.sh

script:
  - . ./tools/ci/build.sh
# FIXME:  - . ./tools/ci/test.sh

env:
  global:
    - CS=dark
    - TRAVIS_SKIP=1
    - TEST_ENV=travis
    - UCONFDIR=$HOME/etc
    - PATH=$PATH:$HOME/bin:$HOME/bin/vendor/.bin:$HOME/usr/bin:$HOME/.local/bin/:/usr/local/bin
    - PYTHONPATH=$PYTHONPATH:$HOME/bin:$HOME/lib/py
      #export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/site-packages
      #export PYTHONPATH=$HOME/.local/lib/python2.7/site-packages:$PYTHONPATH
    - TEST_RESULTS=shippable/testresults/test.tap
    - Build_Deps_Default_Paths=1
  matrix:
    - ENV=noop
    - ENV=dev
    - ENV=testing
    #- ENV=production

branches:
  only: []
  #only:
    #  - master
    #  - '/^test.*$/'
    #  - '/^dev.*$/'
    #  - '/^[0-9]*\.[0-9]*\.[0-9]*/'
  not: []

#deploy:
#  provider: releases
#  api_key: $GH_ACCESS_TOKEN
#  file: script-mpe-$TRAVIS_TAG.tar
#  on:
#    repo: dotmpe/script.mpe
#    tags: true
#    condition: $ENV = production
#
#


