# git-versioning main: script-mpe

- type: application/x-project-mpe
  main: script-mpe
  id: script-mpe
  version: 0.0.0-dev # script-mpe
  environments: [ 'development' ]

  vendor: dotmpe
  distribution: public
  license: GPL

  pd-meta:
    # XXX: what if want to allow Sh here. Or use another project attr. for Sh
    # scripts
    check: ":vchk :bats:specs"
    # TODO: check for /tmp usage, force TMPDIR use
    # TODO: check for XXX tags
    test: ":vchk :-sh:python:test/main.py :bats:specs :bats"

    git-hooks:
      pre-commit: ./tools/git-hooks/pre-commit.sh

    init: "./install-dependencies.sh git:init"

    # FIXME: what about git annex pre-commit .

  environment:
    development:
    - package_pd_meta_default=dev
    - Build_Deps_Default_Paths=1 
    - BOREAS_SKIP=1

