# git-versioning main: script-mpe

- type: application/vnd.dotmpe.project
  main: script-mpe
  id: script-mpe

  version: 0.0.3-dev # script-mpe
  environments: [ 'development' ]

  vendor: dotmpe
  distribution: public
  license: GPL

  pd-meta:
    run:
      behat: "./bin/behat:--tags:~@skip"
      behat-defs: "./bin/behat:-dl"
      # NOTE: behat cannot display outline only
      behat-specs: "./bin/behat:--dry-run:--no-multiline:--no-expand:--tags:~@todo&&~@skip"

    # XXX: what if want to allow Sh here. Or use another project attr. for Sh
    # scripts
    check: "sh:verbose=false:max=385:./tools/sh/tags.sh :verbose=1:vchk :bats:specs ./bin/behat:--dry-run:--no-multiline :git:status"
    # TODO: check for /tmp usage, force TMPDIR use
    test: ":vchk sh:python:test/main.py :bats:specs :bats :bats:test/ubuntu-suite.bats ./bin/behat:--tags:~@skip"
    # TODO: run tests at VM/... if available
    build: ":vagrant:tools/ci/vbox"
    #build: ":vagrant:tools/ci/vbox:ubuntu"

    tasks:
      document: tasks.ttxtm

      tags:
        - TODO # tasks:no-check
        - XXX # tasks:no-check
        - FIXME # tasks:no-check
        - BUG # tasks:no-check
        - NOTE # tasks:no-check

    git-hooks:
      pre-commit: ./tools/git-hooks/pre-commit.sh

    init: "./install-dependencies.sh git:init"

    # FIXME: what about git annex pre-commit .

  environment:
    development:
    - package_pd_meta_default=dev
    - Build_Deps_Default_Paths=1 
    - BOREAS_SKIP=1
    - DANDY_SKIP=1
    - VS1_SKIP=1

  prefixes: {} # See ~/.cllct.rc finfo

  # For make data/*: or move to cllct.rc
  data:
    finfo:
      handlers: # TODO: map to taxus.core.Node annotated/dynamic properties
        - last_updated:mtime
        - last_seen:atime
        # taxus.web.Invariant.mediatype
        - mime_type:lib...

