
id: "http://dotmpe.com/project/script/schema/package#"

description:
type: array
items:
  allOf:
    - type: object
      properties:
        type:
          type: string
        main:
          type: string
        id:
          type: string
        version:
          type: string
        environments:
          type: array
          items: 
            type: string

        pd-meta:
          type: object
  
      required:
        - type
        - id
  
